### ISSUE TITLE
Will it just Run forever?

### ISSUE THREAD

**Issue by sbcrumb** [ezonakiusagi/bht#11]
Not an issue but more of a question I can't find the answer to. Will it ever end on its own? Or will it just keep running forever?
I ask cause I have 2 drives that it has been running on for about 92 hours. So does the process end itself? Or it is up to me to end it?

**Comment by ezonakiusagi** [comment]
I demonstrate the use of this script in my video here:

https://youtu.be/9bh5ZK8z4ZA

It shows that when the runs are all complete, you get an email notification (if email is set and local mail relay is setup).
