### ISSUE TITLE
show_status awk '{gsub(/^/,"\t"); print}' resulting in tabs between every character in output

### ISSUE THREAD

**Issue by rokkoyama** [ezonakiusagi/bht#5]
Mr. Rabbit:

Under Debian 10 (Buster), running bht under ksh93 works great, except the output in --status mode places a tab between every character in the output. Your routine replaces regex /^/ (beginning of a string) with \t, in an attempt to insert a tab at the beginning of each line, but in Debian Buster's included mawk package version 1.3.3-17+b3], it treats each character as the beginning of a string:

print -- "${_smart}" | awk '{gsub(/^/,"\t"); print}'

This results in the following output:

```
HGSTHUS728T8TALE6L4_<sn obscured>:
	badblocks[Testing with pattern 0x00   9.35% done, 68:18:29 elapsed. (0/0/0 errors)]
	H	D	D	 	T	y	p	e	:	[	S	A	T	A	]	
	S	M	A	R	T	:	[	R	e	a	l	l	o	c	a	t	e	d	_	S	e	c	t	o	r	_	C	t	=	0	]	
etc..
```

Confirming this is a direct result of the awk gsub regex /^/:
```
$echo -e "line1\nline2" | awk '{gsub(/^/,"\t"); print}'
	l	i	n	e	1	
	l	i	n	e	2	
```

Testing a solution:
```
$echo -e "line1\nline2" | awk '$0="\t"$0'
	line1
	line2
```

Making the modification to ksh was successful:

print -- "${_smart}" | awk '$0="\t"$0'

Output:
```
HGSTHUS728T8TALE6L4_<sn obscured>:
	badblocks[Testing with pattern 0x00  22.54% done, 69:29:13 elapsed. (0/0/0 errors)]
	HDD Type:[SATA]
	SMART:[Reallocated_Sector_Ct=0]
etc...
```

Btw, I am thoroughly enjoying your HP H220 HBA. Glad you enjoyed the cat photo.

**Comment by ezonakiusagi** [comment]
@rokkoyama thank you for this suggestion. I've incorporated this change and this allows the script to work with both gawk and mawk now.
